package com.bhavani.animelistapp.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class Data(
    val aired: @RawValue Aired,
    val airing: Boolean,
    val approved: Boolean,
    val background: String?,
    val broadcast: @RawValue Broadcast,
    val demographics: @RawValue List<Demographic>,
    val duration: String?,
    val episodes: Int?,
    val explicit_genres: @RawValue List<Any>,
    val favorites: Int?,
    val genres: @RawValue List<Genre>,
    val images: @RawValue Images,
    val licensors: @RawValue List<Licensor>,
    val mal_id: Int?,
    val members: Int?,
    val popularity: Int?,
    val producers: @RawValue List<Producer>,
    val rank: Int?,
    val rating: String?,
    val score: Double,
    val scored_by: Int?,
    val season: String?,
    val source: String?,
    val status: String?,
    val studios: @RawValue List<Studio>,
    val synopsis: String,
    val themes: @RawValue List<Theme>,
    val title: String?,
    val title_english: String?,
    val title_japanese: String?,
    val title_synonyms: List<String>,
    val titles: @RawValue List<Title>,
    val trailer: @RawValue Trailer,
    val type: String,
    val url: String?,
    val year: Int?
): Parcelable {
    constructor() : this(
                Aired("", Prop(From(0, 0, 0), To(0, 0, 0)), "", ""),
                false,
                false,
                "",
                Broadcast("", "", "", ""),
                emptyList(),
                "",
                0,
                emptyList(),
                0,
                emptyList(),
                Images(Jpg("", "", ""), Webp("", "", "")),
                emptyList(),
                0,
                0,
                0,
                emptyList(),
                0,
                "",
                0.0,
                0,
                "",
                "",
                "",
                emptyList(),
                "",
                emptyList(),
                "",
                "",
                "",
                emptyList(),
                emptyList(),
                Trailer("", ImagesX("", "", "", "", ""), "", ""),
                "",
                "",
                0
            )
        }
